const commodities = {
    chemicals: [
        {name:"Aquaponic Treatment",
        buy_price: 5510,
        sell_price: 4640,
        demand: 201234,
        supply: 152345,
        imported_from: "",
        exported_to: ""},
        { name: "Explosives",
        buy_price: 810,
        sell_price: 540,
        demand: 15432,
        supply: 15321,
        imported_from: "",
        exported_to: ""},
        { name: "Hydrogen Fuel",
        buy_price: 145,
        sell_price: 104,
        demand: 1567890,
        supply: 1276543,
        imported_from: "",
        exported_to: ""},
        { name: "Liquid Oxygen",
        buy_price: 1875,
        sell_price: 968,
        demand: 612345,
        supply: 457890,
        imported_from: "",
        exported_to: ""},
        { name: "Pesticides",
        buy_price: 625,
        sell_price: 290,
        demand: 2012345,
        supply: 1765432,
        imported_from: "",
        exported_to: ""},
        { name: "Fertilizer",
        buy_price: 805,
        sell_price: 645,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Synthetic Reagents",
        buy_price: 8775,
        sell_price: 7475,
        demand: 101234,
        supply: 75678 ,
        imported_from: "",
        exported_to: ""},
        { name: "Water",
        buy_price: 725,
        sell_price: 145,
        demand: 5123456,
        supply: 4578901 ,
        imported_from: "",
        exported_to: ""}
    ],
    consumerGoods: [
        { name: "Clothing",
        buy_price: 290,
        sell_price: 135,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Consumer Electronics",
        buy_price: 7160,
        sell_price: 5670,
        demand: 512345,
        supply: 412345,
        imported_from: "",
        exported_to: ""},
        { name: "Furniture",
        buy_price: 1080,
        sell_price: 675,
        demand: 512345,
        supply: 356789,
        imported_from: "",
        exported_to: ""},
        { name: "Household Appliances",
        buy_price: 8750,
        sell_price: 6900,
        demand: 312345,
        supply: 215678,
        imported_from: "",
        exported_to: ""},
        { name: "Survival Equipment",
        buy_price: 805,
        sell_price: 645,
        demand: 101234,
        supply: 75678,
        imported_from: "", 
        exported_to: ""}
    ],
    foods: [
        { name: "Algae",
        buy_price: 72,
        sell_price: 29,
        demand: 5123456,
        supply: 4578901,
        imported_from: "",
        exported_to: ""},
        { name: "Animal Meat",
        buy_price: 435,
        sell_price: 270,
        demand: 2012345,
        supply: 1523456,
        imported_from: "",
        exported_to: ""},
        { name: "Coffee",
        buy_price: 2175,
        sell_price: 1350,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Fish",
        buy_price: 290,
        sell_price: 135,
        demand: 2012345,
        supply: 1523456,
        imported_from: "",
        exported_to: ""},
        { name: "Fruit",
        buy_price: 464,
        sell_price: 343,
        demand: 312345,
        supply: 256789,
        imported_from: "",
        exported_to: ""},
        { name: "Grain",
        buy_price: 72,
        sell_price: 29,
        demand: 4012345,
        supply: 3567890,
        imported_from: "",
        exported_to: ""},
        { name: "Synthetic Meat",
        buy_price: 580,
        sell_price: 290,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Tea",
        buy_price: 725,
        sell_price: 507,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Vegetables",
        buy_price: 145,
        sell_price: 72,
        demand: 3012345,
        supply: 2567890,
        imported_from: "",
        exported_to: ""}
    ],
    industrialMaterials: [
        { name: "Ceramics",
        buy_price: 290,
        sell_price: 135,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Construction Materials",
        buy_price: 375,
        sell_price: 270,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Glass",
        buy_price: 290,
        sell_price: 135,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Insulating Materials",
        buy_price: 13045,
        sell_price: 12650,
        demand: 101234,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Plastic",
        buy_price: 290,
        sell_price: 135,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Polymers",
        buy_price: 575,
        sell_price: 375,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Rubber",
        buy_price: 290,
        sell_price: 135,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Semiconductors",
        buy_price: 3750,
        sell_price: 2700,
        demand: 10123,
        supply: 7567,
        imported_from: "",
        exported_to: ""},
        { name: "Superconductors",
        buy_price: 8050,
        sell_price: 6900,
        demand: 10123,
        supply: 7567,
        imported_from: "",
        exported_to: ""},
        { name: "Wood",
        buy_price: 290,
        sell_price: 135,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""}
    ],
    luxuries: [
        { name: "Artwork",
        buy_price: 14500,
        sell_price: 11600,
        demand: 6123,
        supply: 3567,
        imported_from: "", 
        xported_to: ""},
        { name: "Beer",
        buy_price: 725,
        sell_price: 435,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Exotic Plants",
        buy_price: 2900,
        sell_price: 2175,
        demand: 101234,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Furs",
        buy_price: 12900,
        sell_price: 12175,
        demand: 101234,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Liquor",
        buy_price: 805,
        sell_price: 645,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""},
        { name: "Wine",
        buy_price: 805,
        sell_price: 645,
        demand: 1001234,
        supply: 754321,
        imported_from: "",
        exported_to: ""}
    ],
    machinery: [
        { name: "Agricultural Machinery",
        buy_price: 8970,
        sell_price: 8265,
        demand: 101234,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Articulation Motors",
        buy_price: 5400,
        sell_price: 4050,
        demand: 101234,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Construction Machinery",
        buy_price: 11250,
        sell_price: 9200,
        demand: 101234,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Industrial Droids",
        buy_price: 11500,
        sell_price: 10350,
        demand: 8123,
        supply: 7567,
        imported_from: "",
        exported_to: ""},
        { name: "Mining Machinery",
        buy_price: 10035,
        sell_price: 7500,
        demand: 3123,
        supply: 1767,
        imported_from: "",
        exported_to: ""},
        { name: "Power Tools",
        buy_price: 575,
        sell_price: 435,
        demand: 48123,
        supply: 36567,
        imported_from: "",
        exported_to: ""},
        { name: "Radiation Baffle",
        buy_price: 3335,
        sell_price: 2300,
        demand: 101234,
        supply: 85678,
        imported_from: "",
        exported_to: ""},
        { name: "Thermal Cooling Units",
        buy_price: 4625,
        sell_price: 3750,
        demand: 101234,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Water Purification Units",
        buy_price: 2900,
        sell_price: 2175,
        demand: 81234,
        supply: 64123,
        imported_from: "",
        exported_to: ""}
    ],
    medicines: [
        { name: "Advanced Medicines",
        buy_price: 1740,
        sell_price: 1450,
        demand: 801234,
        supply: 7567,
        imported_from: "",
        exported_to: ""},
        { name: "Aneasthetics",
        buy_price: 805,
        sell_price: 645,
        demand: 601234,
        supply: 456789,
        imported_from: "",
        exported_to: ""},
        { name: "Antibiotics",
        buy_price: 805,
        sell_price: 645,
        demand: 501234,
        supply: 456789,
        imported_from: "",
        exported_to: ""},
        { name: "Bacta",
        buy_price: 1150,
        sell_price: 920,
        demand: 801234,
        supply: 756789,
        imported_from: "",
        exported_to: ""},
        { name: "Basic Medicines",
        buy_price: 625,
        sell_price: 435,
        demand: 801234,
        supply: 756789,
        imported_from: "",
        exported_to: ""},
        { name: "Cybernetic Prosthetics",
        buy_price: 11500,
        sell_price: 10350,
        demand: 80123,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Reanimation Serum",
        buy_price: 43500,
        sell_price: 36250,
        demand: 80123,
        supply: 75678,
        imported_from: "",
        exported_to: ""}
    ],
    metals: [
        { name: "Aluminium",
        buy_price: 986,
        sell_price: 435,
        demand: 801234,
        supply: 756789,
        imported_from: "",
        exported_to: ""},
        { name: "Brass",
        buy_price: 625,
        sell_price: 290,
        demand: 801234,
        supply: 756789,
        imported_from: "",
        exported_to: ""},
        { name: "Bronzium",
        buy_price: 2250,
        sell_price: 1725,
        demand: 101234,
        supply: 56789,
        imported_from: "",
        exported_to: ""},
        { name: "Carbonite",
        buy_price: 1150,
        sell_price: 920,
        demand: 271234,
        supply: 201234,
        imported_from: "",
        exported_to: ""},
        { name: "Copper",
        buy_price: 625,
        sell_price: 290,
        demand: 1001234,
        supply: 756789,
        imported_from: "",
        exported_to: ""},
        { name: "Desh",
        buy_price: 1150,
        sell_price: 920,
        demand: 271234,
        supply: 201234,
        imported_from: "",
        exported_to: ""},
        { name: "Durasteel",
        buy_price: 2500,
        sell_price: 1875,
        demand: 101234,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Frasium",
        buy_price: 1150,
        sell_price: 920,
        demand: 271234,
        supply: 201234,
        imported_from: "",
        exported_to: ""},
        { name: "Gold",
        buy_price: 1150,
        sell_price: 920,
        demand: 271234,
        supply: 201234,
        imported_from: "",
        exported_to: ""},
        { name: "Inoxium",
        buy_price: 2530,
        sell_price: 2300,
        demand: 60123,
        supply: 25678,
        imported_from: "",
        exported_to: ""},
        { name: "Iron",
        buy_price: 920,
        sell_price: 460,
        demand: 801234,
        supply: 756789,
        imported_from: "",
        exported_to: ""},
        { name: "Lithium",
        buy_price: 1150,
        sell_price: 920,
        demand: 271234,
        supply: 201234,
        imported_from: "",
        exported_to: ""},
        { name: "Platinum",
        buy_price: 3750,
        sell_price: 2070,
        demand: 271234,
        supply: 201234,
        imported_from: "",
        exported_to: ""},
        { name: "Silver",
        buy_price: 1150,
        sell_price: 920,
        demand: 271234,
        supply: 201234,
        imported_from: "",
        exported_to: ""},
        { name: "Titanium",
        buy_price: 2500,
        sell_price: 1875,
        demand: 101234,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Tungsten",
        buy_price: 2500,
        sell_price: 1875,
        demand: 101234,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Ultrachrome",
        buy_price: 1150,
        sell_price: 920,
        demand: 271234,
        supply: 201234,
        imported_from: "",
        exported_to: ""}],
    minerals: [
        { name: "Alum",
        buy_price: 5050,
        sell_price: 4640,
        demand: 4012,
        supply: 3567,
        imported_from: "",
        exported_to: ""},
        { name: "Ardanium",
        buy_price: 6615,
        sell_price: 6075,
        demand: 3012,
        supply: 2567,
        imported_from: "",
        exported_to: ""},
        { name: "Benitoite",
        buy_price: 8700,
        sell_price: 6265,
        demand: 2012,
        supply: 1567,
        imported_from: "",
        exported_to: ""},
        { name: "Chronamite",
        buy_price: 11500,
        sell_price: 9200,
        demand: 1012,
        supply: 512,
        imported_from: "",
        exported_to: ""},
        { name: "Grandidierite",
        buy_price: 127600,
        sell_price: 92000,
        demand: 101,
        supply: 52, 
        imported_from: "",
        exported_to: ""},
        { name: "Kunda",
        buy_price: 4205,
        sell_price: 3225,
        demand: 5012,
        supply: 4012,
        imported_from: "",
        exported_to: ""},
        { name: "Low Temperature Diamond",
        buy_price: 55100,
        sell_price: 40250,
        demand: 101,
        supply: 52,
        imported_from: "",
        exported_to: ""},
        { name: "Mirkanite",
        buy_price: 11500,
        sell_price: 9200,
        demand: 1012,
        supply: 512,
        imported_from: "",
        exported_to: ""},
        { name: "Painite",
        buy_price: 103500,
        sell_price: 92000,
        demand: 101,
        supply: 52,
        imported_from: "",
        exported_to: ""},
        { name: "Rock Ivory",
        buy_price: 11500,
        sell_price: 9200,
        demand: 1012,
        supply: 512,
        imported_from: "",
        exported_to: ""},
        { name: "Teniline",
        buy_price: 57500,
        sell_price: 40250,
        demand: 50123,
        supply: 5123,
        imported_from: "",
        exported_to: ""},
        { name: "Void Opals",
        buy_price: 230000,
        sell_price: 207000,
        demand: 101,
        supply: 52,
        imported_from: "",
        exported_to: ""}
    ],
    technology: [
        { name: "Advanced Catalysers",
        buy_price: 3915,
        sell_price: 3450,
        demand: 100123,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Auto Fabricators",
        buy_price: 6360,
        sell_price: 6210,
        demand: 10123,
        supply: 7567,
        imported_from: "",
        exported_to: ""},
        { name: "Bioreducing Lichen",
        buy_price: 2135,
        sell_price: 1125,
        demand: 100123,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Computer Components",
        buy_price: 920,
        sell_price: 692,
        demand: 100123,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Medical Diagnostic Equipment",
        buy_price: 3875,
        sell_price: 3500,
        demand: 80123,
        supply: 65678,
        imported_from: "",
        exported_to: ""},
        { name: "Muon Imager",
        buy_price: 8715,
        sell_price: 6900,
        demand: 10123,
        supply: 7567,
        imported_from: "",
        exported_to: ""},
        { name: "Structural Regulators",
        buy_price: 3375,
        sell_price: 2750,
        demand: 491234,
        supply: 456789,
        imported_from: "",
        exported_to: ""},
        { name: "Telemetry Suite",
        buy_price: 3875,
        sell_price: 3500,
        demand: 80123,
        supply: 65678,
        imported_from: "",
        exported_to: ""}
    ],
    textiles: [
        { name: "Conductive Fabrics",
        buy_price: 1260,
        sell_price: 1035,
        demand: 100123,
        supply: 75678,
        imported_from: "",
        exported_to: ""},
        { name: "Leather",
        buy_price: 435,
        sell_price: 290,
        demand: 901234,
        supply: 876543,
        imported_from: "",
        exported_to: ""},
        { name: "Natural Fabrics",
        buy_price: 1125,
        sell_price: 625,
        demand: 810123,
        supply: 775678, 
        imported_from: "",
        exported_to: ""},
        { name: "Synthetic Fabrics",
        buy_price: 573,
        sell_price: 435,
        demand: 2001234,
        supply: 1556789,
        imported_from: "",
        exported_to: ""}
    ]
}

export default commodities;